import { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Share2, Calendar, MapPin, Users, Trophy, Download } from 'lucide-react';

const WrappedCard = ({ isActive }: { isActive: boolean }) => (
  <div className={`relative w-full max-w-sm mx-auto transition-all duration-500 ${
    isActive ? 'scale-100 opacity-100' : 'scale-95 opacity-60'
  }`}>
    <Card className="glass-card overflow-hidden">
      <CardContent className="p-0">
        {/* Header */}
        <div className="bg-gradient-primary p-6 text-center">
          <h3 className="text-2xl font-bold text-white mb-2">Your 2025</h3>
          <p className="text-white/80">Social Wrapped</p>
        </div>

        {/* Stats */}
        <div className="p-6 space-y-6">
          <div className="text-center">
            <div className="text-5xl font-bold gradient-text mb-2">247</div>
            <p className="text-muted-foreground">New People Met</p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="text-center">
              <div className="text-2xl font-bold text-neon-cyan mb-1">12</div>
              <p className="text-xs text-muted-foreground">Cities Visited</p>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-neon-magenta mb-1">4.2k</div>
              <p className="text-xs text-muted-foreground">XP Earned</p>
            </div>
          </div>

          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <MapPin className="w-4 h-4 text-electric-violet" />
                <span className="text-sm">Top Location</span>
              </div>
              <span className="text-sm font-semibold">Berlin</span>
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4 text-neon-cyan" />
                <span className="text-sm">Best Month</span>
              </div>
              <span className="text-sm font-semibold">October</span>
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Trophy className="w-4 h-4 text-neon-magenta" />
                <span className="text-sm">Streak Record</span>
              </div>
              <span className="text-sm font-semibold">28 days</span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-matrix-surface/50">
          <p className="text-xs text-center text-muted-foreground">
            Generated by MaetriXs Social Tracker
          </p>
        </div>
      </CardContent>
    </Card>
  </div>
);

export const MaetrixsWrapped = () => {
  const [currentCard, setCurrentCard] = useState(0);
  const totalCards = 3;

  return (
    <section className="py-20 bg-matrix-dark">
      <div className="container mx-auto px-6">
        {/* Section Header */}
        <div className="text-center mb-16">
          <Badge variant="outline" className="mb-4 px-4 py-2 text-electric-violet border-electric-violet/30">
            <Share2 className="w-4 h-4 mr-2" />
            Coming Soon
          </Badge>
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            <span className="gradient-text-secondary">MaetriXs Wrapped</span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
            Get a beautiful, shareable summary of your social year. 
            See your networking journey, top locations, and connection milestones.
          </p>
        </div>

        {/* Wrapped Card Display */}
        <div className="flex flex-col lg:flex-row items-center gap-12">
          {/* Card Viewer */}
          <div className="lg:w-1/2">
            <WrappedCard isActive={true} />
            
            {/* Card Navigation */}
            <div className="flex justify-center gap-2 mt-6">
              {Array.from({ length: totalCards }).map((_, index) => (
                <button
                  key={index}
                  className={`w-3 h-3 rounded-full transition-all duration-300 ${
                    index === currentCard 
                      ? 'bg-neon-cyan shadow-neon-cyan' 
                      : 'bg-matrix-border hover:bg-matrix-border'
                  }`}
                  onClick={() => setCurrentCard(index)}
                />
              ))}
            </div>
          </div>

          {/* Features List */}
          <div className="lg:w-1/2 space-y-6">
            <div className="space-y-4">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-neon-cyan/10 flex items-center justify-center">
                  <Users className="w-6 h-6 text-neon-cyan" />
                </div>
                <div>
                  <h3 className="font-semibold text-foreground mb-2">Personal Stats</h3>
                  <p className="text-muted-foreground">Total connections, cities visited, XP earned, and more.</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-neon-magenta/10 flex items-center justify-center">
                  <MapPin className="w-6 h-6 text-neon-magenta" />
                </div>
                <div>
                  <h3 className="font-semibold text-foreground mb-2">Location Insights</h3>
                  <p className="text-muted-foreground">Discover your top networking cities and connection hotspots.</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-electric-violet/10 flex items-center justify-center">
                  <Share2 className="w-6 h-6 text-electric-violet" />
                </div>
                <div>
                  <h3 className="font-semibold text-foreground mb-2">Share & Export</h3>
                  <p className="text-muted-foreground">Share your social achievements or download for your portfolio.</p>
                </div>
              </div>
            </div>

            <div className="flex gap-4 pt-4">
              <Button className="btn-primary flex-1">
                <Download className="w-4 h-4 mr-2" />
                Get Early Access
              </Button>
              <Button variant="outline" className="btn-outline">
                <Share2 className="w-4 h-4 mr-2" />
                Preview
              </Button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};